### ISSUE TITLE
Why to hardcode model properties?

### ISSUE THREAD

**Issue by mrvnklm** [stefanvanherwijnen/quasar-app-extension-http-authentication#16]
Hey there, I wanted to use your extension but I was wondering why you hardcoded the user model properties in a way, that requires to adjust backend functionality. It just took me some time to figure out why it is not working, which could be prevented by some adjustments or at least add some definitions in the readme.

1. Why use `data.body` instead of just `data` to allow direct input of the object without unessesary `body` property?
2. Why don't just store the `response.data` object, or at least `response.data.user`? Using another `data` is not needed and makes the extension not usable out of the box for most people, which have a basic login functionality / layout.
```
axiosInstance
      .post(LOGIN_ROUTE, data.body)
      .then(response => {
        state.commit('setUser', response.data.user.data)
```
3. Why use *another* nested property `attributes` which makes probably a lot of people having to debug why the user is not stored / returned properly?
4. How about make roles an optional argument? Not everybody is using a role based authentication, which causes additional work to add some "dummy role"?
```
userData: (data) => {
    return {
      id: data.id,
      email: data.attributes.email,
      name: data.attributes.name,
      roles: data.attributes.roleNames
    }
```

**Comment by stefanvanherwijnen** [comment]
Thanks for the feedback.

> 
>     1. Why use `data.body` instead of just `data` to allow direct input of the object without unessesary `body` property?
> 
Because `data` also contains the `rememberMe` boolean. This however isn't necessary so I'll change it.

>     2. Why don't just store the `response.data` object, or at least `response.data.user`? Using another `data` is not needed and makes the extension not usable out of the box for most people, which have a basic login functionality / layout.
Some logic depends on the `user` variable. E.g. if your backend does not return an `email` field, things will break. For some flexibility I added the userData() function.

>     1. Why use _another_ nested property `attributes` which makes probably a lot of people having to debug why the user is not stored / returned properly?

This is because I use JSON-API myself.

>     2. How about make roles an optional argument? Not everybody is using a role based authentication, which causes additional work to add some "dummy role"?
> 

You can use your own `user` object with the `setUserData()` function. E.g.
```
setUserData((data) => ({
      id: data.id,
      email: data.email,
      name: data.name
})
```

Have a look at `userData` and `setUserData`. I'm currently rewriting the whole app extension so feedback on this subject is appreciated, as I tried to add some flexibility but for my use case I don't need it so I can't properly test it for functionality.
If you could let me know what your backend returns and what information from it you need to use in the AE, I'll try to find a way to incorporate it.

**Comment by mrvnklm** [comment]
After considering the use of JSON-API and having a better understanding through reading your explanations I am quite fine with how you designed the whole thing and I will adjust my backend. Thank you for your time!
