### ISSUE TITLE
Overwrite some functionality of store vuex files

### ISSUE THREAD

**Issue by 3kynox** [stefanvanherwijnen/quasar-app-extension-http-authentication#5]
Hello!

I'm looking to change the login parameters to pass through headers instead of a payload.
To achieve this, I need to edit store/actions.js on the extension folder.
Unfortunately, I was forced to make these changes on node_modules/Extension folder and I would like to be able to rewrite the necessary file(s) in my project folder. Further modifications for other actions could be needed as well.

Is there any way to achieve this?

Thanks anyway.

**Comment by stefanvanherwijnen** [comment]
Can you give this a try:
https://github.com/stefanvanherwijnen/quasar-app-extension-auth-token-based/tree/httpauthentication

I believe the Basic authentication scheme is what you were after. Remember me functionality won't work because I think it is not a good idea to store credentials in a cookie.

**Comment by stefanvanherwijnen** [comment]
Should be fixed or no longer applicable in v2.
